{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orion.fullname" . }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }} {{ if not .Values.api.postgres.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }} {{ end }}
  selector:
    matchLabels:
      {{- include "orion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orion.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.server.enabled -}}
        - name: api
            securityContext:
                {{- toYaml .Values.api.securityContext | nindent 12 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
            command: ["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "WARNING"]
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
            - containerPort: 4200
            resources:
                {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.nodeSelector }}
        env:
            
        nodeSelector:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.agent.enabled -}}
        - name: agent
            securityContext:
                {{- toYaml .Values.agent.securityContext | nindent 12 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}" #prefecthq/prefect:2.0b2-python3.8
            command: ["prefect", "agent", "start", "{{ .Values.agent.workQueueName }}"]
            imagePullPolicy: "IfNotPresent"
            env:
            - name: PREFECT_API_URL
                value: http://orion:4200/api
        {{- end }}
{{- end }}


