apiVersion: v1
kind: Secret
metadata:
  name: {{- include "orion.postgres-secret-name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
type: Opaque
data:
  connection-string: {{- include "orion.postgres-connstr" . }}