{{- if .Values.agent.enabled }}
apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ include "orion.fullname" . }}-agent
  labels:
    {{- include "orion.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "orion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orion.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["prefect", "agent", "start", {{ .Values.agent.workQueueName }}]
          env:
          {{- if and .Values.api.enabled  }}
          - name: PREFECT_API_URL
            value: "http://{{ include "orion.fullname" . }}:{{ .Values.api.port }}/api"
          {{- else }}
          - name: PREFECT_API_URL
            value: "https://beta.prefect.io/api/accounts/{{ .Values.prefectAccount }}/workspaces/{{ .Values.prefectWorkspaceId }}"
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
